name: Docker Build
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - run: docker build --tag 432916826401.dkr.ecr.us-west-2.amazonaws.com/sec-cron:latest .
        - name: Push to ECR
          id: ecr
          uses: jwalton/gh-ecr-push@v2
          with:
            access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            region: us-west-2
            image: sec-cron:latest